language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: RqJ2kYLUr5/OpPTlAbgLyGaMw2PzvMZLyQo2JbeG8mn5npiIX5UqN3CcjpH0u3dcXDrdE1Hii/ksGfwTxOmceR4Mk/avPlxZCdcZZ70i8UnvNR9H38GigoPzdzLr3NkGJXlFrA/7G4BrTWPVMC/kD0ss+JEwUGp1kGKaH8DgOhAUQKc+zyxFjybgiOLz4B293GnCsiTWSI1cKU6MqPt24OEIlSVsYD9arOoJR06+/0TrcffCvy6LAW4Jxg17MDHE9SCO6y61TC4MVbOwnkOyhFe5NjL4/nyNTF12UEQbuzO44sFsA/W1YWyQXpLlfA+iTGubeez2bW8NIjNmTams6qXipS4ZONWuRHmdz/eeDzlhXKxzHlGvI6e1+9v3COVcWi1LtrxBKTy0cDVIyWvRXGwT9PcAPLfdGrxQ9A51jYoFHU4sS5fk1lg7Jwv7kzdy/pNfM/jwfgJdOvG+XgU7CMlOZzzXEfd9V4mVT2ozwh0XFgYgztVS19tdU01d8ct6DB3stB+ti+u6a4wZ8Zr8q5c5Op3icd9M6aGHRqm0MN3ra2HZHCtd/d5ZaZD1jHhL1gAtyfI5oCfMRetDUhfgX4VkzsCjbkm0Hywx5V9uj97c4N/spVqehPucmRUrhIleIYJ2RJYhWhrOCN4jAu1/w41Vp7v/DYjGCT+lxwVUy1Y=
  app: 'seha-noteful-v4'
  on:
    repo: thinkful-ei19/seha-noteful-v4
